name: Publish NPM

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 16.x

jobs:
  publish:
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install
        run: npm i
      - name: Build
        run: npm run build
      - name: Publishing
        uses: JS-DevTools/npm-publish@v2
        with:
          token: ${{ secrets.NPM_TOKEN }}
