name: Publish NPM

on: workflow_dispatch

env:
  NODE_VERSION: 16.x

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: install rush
        run: npm install -g @microsoft/rush
      - name: Install dependencies
        run: rush update
      - name: rush Build
        run: rush rebuild
      - name: Publishing mono repo 1
        uses: JS-DevTools/npm-publish@v2
        id: publish_mono
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/npm-auto-publish-test-mono-repo-1
      - name: Publishing mono repo 2
        uses: JS-DevTools/npm-publish@v2
        id: publish_mono_type
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./packages/npm-auto-publish-test-mono-repo-2
      - name: Set output vars
        run: |
          echo "MONO_A={{ !!steps.publish_mono.outputs.value }}" >> "$GITHUB_OUTPUT"
          echo "MONO_B={{ !!steps.publish_mono_type.outputs.value }}" >> "$GITHUB_OUTPUT"
  check-mono:
    name: Test A
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: publico
        run: |
          echo "${{ needs.publish.outputs.MONO_A }}"
          if [[ !needs.publish.outputs.MONO_A ]]; then
            echo "Publication Error: Both packages failed to publish. Did you changed package.json version? Please review and try again."
            exit 1
          else
            echo "Version A published"
            exit 0
          fi

  check-mono-b:
    name: Test b
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: publico
        run: |
          echo "${{ needs.publish.outputs.MONO_B }}"
          if [[ !needs.publish.outputs.MONO_B ]]; then
            echo "Publication Error: Both packages failed to publish. Did you changed package.json version? Please review and try again."
            exit 1
          else
            echo "Version A published"
            exit 0
          fi
