name: Publish NPM

on: workflow_dispatch

env:
  NODE_VERSION: 16.x

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    environment: development
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Config Git Properties
        run: |
          git config --local user.email ${{ secrets.EMAIL }}
          git config --local user.name ${{ secrets.AUTO_PUSH_NAME }}
      - name: Install Rush
        run: npm install -g @microsoft/rush
      - name: Verify Change Logs
        run: rush change --verify
      - name: Update package.json version
        run: rush version --bump
      - name: Install dependencies
        run: rush update
      - name: rush Build
        run: rush rebuild
      - name: Rush Publish
        run: rush publish --apply --target-branch main --publish --npm-auth-token ${{ secrets.NPM_TOKEN }} --add-commit-details --include-all
      - name: Commit and Push package.json version update
        run: |
          git add .
          git commit -m "Update package.json version"
          git push
